### ISSUE TITLE
nestJs build 제외 필요

### ISSUE THREAD

**Issue by nkwoo** [ErrUnknownSignal/youtube2gif#3]
현재 nest serve로 실행시 dist폴더에 build 되는데 하위 Angular 소스들까지 build되는 이슈가 있음.

**Comment by ErrUnknownSignal** [comment]
this issue will be fix next commit, hold on

```
//tsconfig.build.json
"exclude": ["node_modules", "test", "dist", "**/*spec.ts", "angular"]
```

**Comment by ErrUnknownSignal** [comment]
fixed  ErrUnknownSignal/youtube2gif@6c36307975bbf1a76eeb27fae310c8a0513d6579
